config/routes.rb
Rails.application.routes.draw do
  resources :attendances

  resources :plans
  get 'plans/:id/addattendee' => 'plans#addattendee', as: :addattendee
  get 'plans/:id/calculate' => 'plans#calculate', as: :calculate
  get 'plans/:id/plan4dinkum' => 'plans#plan4dinkum', as: :plan4dinkum
  put 'plans/:id/suggest' => 'plans#suggest', as: :suggest
  put 'plans/:id/close' => 'plans#close', as: :close

  resources :users
  
  resources :sessions
  
  root 'plans#index'

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  validates :start_datum, :end_datum, :presence => true
  has_many :attendances,:dependent => :destroy
  has_many :users, through: :attendances

  accepts_nested_attributes_for :attendances, reject_if: proc { |attributes| attributes['user_id'].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :users

  def calculate
    # Teilnehmerliste bilden
    tn = {}

    self.users.each do |u|
      name = u.vname + " " + u.nname.first + "."
      u.blockdaten ? blockwochen = blockwochen_finden(u.blockdaten,self.jahr) : blockwochen = []
      tn[name] = blockwochen
    end
    
    folge = folge_berechnen(tn,self.jahr)
    return folge
  end

  private
#####
## Uebersetzung der eingegebenen Blockdaten in KWs
#####

  def blockwochen_finden(blockdaten,jahr)
    blockdaten.gsub!(/,/, "\n")
    blockdaten.gsub!(/bis/, "-")
    blockdaten.gsub!(/ */, "")
    blockwochen = []

    blockdaten.split(/[\r]?\n/).each do |zeile|
      case zeile
      when /^KW(\d\d?)$/
        # KW14
        blockwochen << /^KW(\d\d?)$/.match(zeile)[1].to_i
      when /^KW(\d\d?)\W(KW)?(\d\d?)$/
        # KW13-KW16 oder KW12/KW13
        start, kw, ende = /^KW(\d\d?)\W(KW)?(\d\d?)$/.match(zeile).captures
        blockwochen += (start.to_i..ende.to_i).to_a
      when /^ungeradeWochen$/
        blockwochen += (1..51).step(2).to_a
        # falls 53 Wochen
        blockwochen << 53 if "31.12.#{jahr}".to_date.cweek == 53
      when /^geradeWochen$/
        blockwochen += (2..52).step(2).to_a
      when /^\d\d?\.\d\d?\.(\d\d(\d\d)?)?$/
        # 31.10.14 oder 31.10. oder 31.10.2014
        Rails.logger.warn "date-parser für : #{zeile}\n"
        da = zeile.split(".")
        da.last.prepend("20") if (da.size == 3 && da.last =~ /\d\d/)
        blockwochen << da.reverse!.join("-").to_date.cweek
      when /^\d\d?\.\d\d?\.(\d\d(\d\d)?)?-\d\d?\.\d\d?\.(\d\d(\d\d)?)?$/
        # 5.4.2014-21.4.2014 oder 5.4.14-21.4.14 oder 5.4.-21.4.
        daten = zeile.split("-")
        startd = daten[0].split(".")
        if startd.size == 3
          startd.last.prepend("20") if (startd.size == 3 && startd.last =~ /\d\d/)
        else
          startd[2] = jahr
        end
        endd = daten[1].split(".")
        if endd.size == 3
          endd.last.prepend("20") if (endd.size == 3 && endd.last =~ /\d\d/)
        else
          endd[2] = jahr
        end
        startw = startd.reverse!.join("-").to_date.cweek
        endw = endd.reverse!.join("-").to_date.cweek
        blockwochen += (startw..endw).to_a
      end
    end
    blockwochen.uniq.sort if blockwochen.size > 0
    return blockwochen
  end

#####
## Prio nach Anzahl der bish. Einsaetze und Anzahl der geblockten Termine
#####
  def prio_bilden(tn,folge,ges_einsaetze,ger_schalter)
    namen = []
    tln = {}
    einsaetze_pp = folge.each_with_object(Hash.new(0)) { |name,anzahl| anzahl[name] += 1}
    durchschnt_eins = folge.size * 1.0 / tn.size
    if ger_schalter == 0
      durchschnt_eins += 1
    end
    tn.keys.each do |person|
      if einsaetze_pp[person] <= durchschnt_eins && einsaetze_pp[person] <= ges_einsaetze / tn.size
        tln[person] = tn[person].size * 20 + einsaetze_pp[person] * 100 / durchschnt_eins
      end
    end
    tln = Hash[tln.sort_by{ |n,bw| bw }.reverse]
    tln.keys.each do |n|
      namen << n
    end
    return namen
  end

#####
## Berechnung der Folge unter Beruecksichtigg. der geblockten Termine
#####
  def folge_berechnen(tn,jahr)
    folge = [ "" ]
    ges_einsaetze = "28.12.#{jahr}".to_date.cweek
    ger_schalter = 1
    namen = prio_bilden(tn,folge,ges_einsaetze,ger_schalter)
    zaehler = 0
    while folge.size <= ges_einsaetze
      namen.each do |name|
        unless tn[name].find_index(folge.size) || folge.size > ges_einsaetze
          folge << name
          zaehler += 1
        end
      end
      if zaehler == 0
        if namen.size < tn.size && ger_schalter == 1
          ger_schalter = 0
        else
          folge << "nicht besetzt!"
          ger_schalter = 1
        end
      end
      zaehler = 0
      namen = prio_bilden(tn,folge,ges_einsaetze,ger_schalter)
    end
    return folge 
  end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :calculate, :suggest, :close, :plan4dinkum, :addattendee, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
    @plan = Plan.where(:jahr => Date.today.year).first
    if @plan && @plan.folge 
      @folge = @plan.folge.split(",")
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    if @plan.folge 
      @folge = @plan.folge.split(",")
    else
      @folge = []
    end
    @auslastung = attendeesload(@folge)
  end

  def plan4dinkum
    @folge = @plan.folge.split(",")
  end

  # GET /plans/new
  def new
    @plan = Plan.new
    # some defaults - should be changed later on
    Plan.last ? @plan.jahr = Plan.last.jahr + 1 : @plan.jahr = Time.now.year + 1
    @plan.start_datum = "#{@plan.jahr}-01-01"
    @plan.end_datum = "#{@plan.jahr}-12-31"
    @plan.wochentage = "1,2,3,4,5,6"
  end

  def addattendee
    if params[:todo] == "tn"
      @plan.attendances.where(user_id: params[:user_id]).first.destroy
    else
      @plan.attendances.create(user_id: params[:user_id])
    end
    redirect_to @plan
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json

  def calculate
    @folge = @plan.calculate
    @auslastung = attendeesload(@folge)
    respond_to do |format|
      format.js
    end
  end

  def suggest
    @plan.update(folge: params[:folge].join(","))
    redirect_to @plan
  end

  def close
    @plan.update(abgenommen: true)
    # attendees dates leeren und mit Weihnachtsdefaults füllen
    redirect_to @plan
  end

  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: "Plan was successfully created. Now let's add some attendees." }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:jahr, :start_datum, :end_datum, :wochentage, {attendances_attributes: [:id, :plan_id, :user_id, :_destroy]}, :folge, :abgenommen)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label "Jahr" %><br>
    <%= f.text_field :jahr %>
  </div>
  <% f.text_field :wochentage %>
  <% f.text_field :wechsel %>
  <div class="field">
    <%= f.label "Startdatum" %><br>
    <%= f.date_field :start_datum %>
  </div>
  <div class="field">
    <%= f.label "Enddatum" %><br>
    <%= f.date_field :end_datum %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/plans/_plan.html.erb
<div id="plan">
<% if @plan.abgenommen %>
  <article>
    <strong>Teilnehmer(<%= @plan.attendances.size %>):</strong>
    <% @plan.attendances.each do |a| %>
      <%= "#{a.user.vname} #{a.user.nname.first}." %>
    <% end %>
  </article>
<% else %>
  <article>
    <strong>mögliche Teilnehmer (<%= User.aktuell.size %>)</strong>
    <menu>
      <%= link_to "(neu) berechnen", calculate_path(@plan), remote: true %><br>
      <%= link_to "so vorschlagen", suggest_path(folge: @folge, id: @plan.id), method: "put" %><br>
      <%= link_to "OK, so übernehmen", close_path(id: @plan.id), method: "put" %><br>
      <% if @plan.folge %>
        <%= link_to "Plan für Dinkum anzeigen", plan4dinkum_path(id: @plan.id) %>
      <% end %>
    </menu>
  </article> 
  <ul class="attendees">
    <% User.aktuell.order('nname').each do |user| %>
      <% uname =  user.vname + " " + user.nname.first + "." %>
      <% if @plan.attendances.any? { |attendance| attendance.user_id == user.id } %>
        <% cl = "tn" %>
        <% link = "( #{@auslastung[uname]} )" %>
      <% else %>
        <% cl = "ntn" %>
        <% link = "" %>
      <% end %>
      <li>
        <table class="attendee">
          <tr>
            <td class="name"><%= link_to uname, edit_user_url(user) %></td>
            <td class="checkbox"><%= link_to link, addattendee_path(id: @plan.id, user_id: user.id, todo: cl), class: cl %></td>
          </tr>
        </table>
      </li>
    <% end %>
    <li><%= link_to "Beteiligte", users_path(plan: @plan) %></li>
  </ul>
<% end %>
<hr>
<br>
  <% (@plan.start_datum.month..@plan.end_datum.month).each do |monat| %>  
    <article class="monat">
      <table>
        <tr>
          <th colspan="9" style="text-align: left; font-weight:bold; "><%= monate[monat] %></th>
        </tr>
        <tr class="kopf">
          <td class="wn"><%= (@plan.wechsel == 1)? "KW" : "R" %></td>
          <% c = 0 %>
          <% 7.times do %>
            <td><%= (@plan.wechsel + c) <= 7? wochentage[@plan.wechsel + c].slice(0..1) : wochentage[@plan.wechsel + c - 7].slice(0..1) %></td>
            <% c = c+1 %>
          <% end %>
          <td></td>
        </tr>
        <% w = Date.new(@plan.jahr,monat).monday %>
        <% while (w.month <= monat && w.year <= @plan.jahr) || (w.month == 12 && w.year < @plan.jahr) do %>
          <% if w.cweek == Date.today.cweek && w.year == Date.today.year %>
            <tr class="aktuell">
          <% else %>
            <tr>
          <% end %>
            <td class="wn"><%= w.cweek %></td>
            <% (1..7).each do |wt| %>
              <% if (w + (wt - 1)) == Date.today %>
                <td class="heute">
              <% else %>
                <td class="dom">
              <% end %>
              <%= (w + (wt - 1)).strftime("%d") %>
            </td>
            <% end %>
            <% if @folge && !( monat == 12 && w.cweek == 1 ) && @folge[w.cweek] == "nicht besetzt!"%>
            <td class="nicht_besetzt">
            <% else %>
            <td>
            <% end %>
            <% if @folge && !( monat == 12 && w.cweek == 1 ) %>
              <%= @folge[w.cweek] %>
            <% end %>
            </td>
          </tr>
          <% w = w+7 %>
        <% end %>
      </table>
    </article>
  <% end %>
</div>

app/views/plans/_tn_liste.html.erb
<%= f.fields_for @users do %>
  <%= render "user", f: f %>
<% end %>

app/views/plans/_user.html.erb
<tr>
  <td>
    <div class="field">
      <%= f.text_field :vname %>
    </div>
  </td>
  <td>
    <div class="field">
      <%= f.text_field :nname %>
    </div>
  </td>
  <td>
    <div class="field">
      <%= f.text_field :email %>
    </div>
  </td>
  <td>
    <div class="field">
      <%= f.text_area :blockdaten %>
    </div>
  </td>
  <td>
    <%= f.check_box :_destroy %>
    <%= f.label :_destroy, "Remove" %>
  </td>
</tr>

app/views/plans/addattendee.html.erb
<%= form_for @plan do |f| %>
  <% User.aktuell.order('nname').each do |user| %>
    <% flag = @plan.attendances.any? { |attendance| attendance.user_id == user.id } %>
    <%= user.vname + " " + user.nname.first + ". " %>
    <%= check_box_tag "plan[attendances_attributes][][user_id]", user.id, flag %><br>
  <% end %>



  <%= f.submit %>
<% end %>

app/views/plans/calculate.js.erb
$("#plan").html('<%= escape_javascript(render 'plan') %>')

app/views/plans/edit.html.erb
<aside class="fr">
  <%= link_to 'Show', @plan %><br>
  <%= link_to 'Destroy', @plan, method: :delete, data: { confirm: 'Are you sure?' } %><br>

</aside>
<h1>Editing plan</h1>

<%= render 'form' %>

app/views/plans/index.html.erb
<br>
<% if @plan %>
  <h2>Plan für <%= @plan.jahr %></h2>
  <article>
    <strong>Teilnehmer(<%= @plan.attendances.size %>):</strong>
    <% @plan.attendances.each do |a| %>
      <%= "#{a.user.vname} #{a.user.nname.first}." %>
    <% end %>
  </article>
<hr>
<br>
  <% (@plan.start_datum.month..@plan.end_datum.month).each do |monat| %>  
    <article class="monat">
      <table>
        <tr>
          <th colspan="9" style="text-align: left; font-weight:bold; "><%= monate[monat] %></th>
        </tr>
        <tr class="kopf">
          <td class="wn"><%= (@plan.wechsel == 1)? "KW" : "R" %></td>
          <% c = 0 %>
          <% 7.times do %>
            <td><%= (@plan.wechsel + c) <= 7? wochentage[@plan.wechsel + c].slice(0..1) : wochentage[@plan.wechsel + c - 7].slice(0..1) %></td>
            <% c = c+1 %>
          <% end %>
          <td></td>
        </tr>
        <% w = Date.new(@plan.jahr,monat).monday %>
        <% while (w.month <= monat && w.year <= @plan.jahr) || (w.month == 12 && w.year < @plan.jahr) do %>
          <% if w.cweek == Date.today.cweek && w.year == Date.today.year %>
            <tr class="aktuell">
          <% else %>
            <tr>
          <% end %>
            <td class="wn"><%= w.cweek %></td>
            <% (1..7).each do |wt| %>
              <% if (w + (wt - 1)) == Date.today %>
                <td class="heute">
              <% else %>
                <td class="dom">
              <% end %>
              <%= (w + (wt - 1)).strftime("%d") %>
            </td>
            <% end %>
            <% if @folge && !( monat == 12 && w.cweek == 1 ) && @folge[w.cweek] == "nicht besetzt!"%>
            <td class="nicht_besetzt">
            <% else %>
            <td>
            <% end %>
            <% if @folge && !( monat == 12 && w.cweek == 1 ) %>
              <%= @folge[w.cweek] %>
            <% end %>
            </td>
          </tr>
          <% w = w+7 %>
        <% end %>
      </table>
    </article>
  <% end %>
</div>
<% else %>
  <h2>Es ist kein Plan für das laufende Jahr im System erfasst.</h2>
<% end %>

app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/plan4dinkum.html.erb
h1. <%= @plan.jahr %>
<% (@plan.start_datum.month..@plan.end_datum.month).each do |monat| %>  
  <br>
  <br>
    || <%= monate[monat] %> ||<br>
    || <%= (@plan.wechsel == 1)? "KW" : "R" %> ||
    <% c = 0 %>
    <% 7.times do %>
      <%= (@plan.wechsel + c) <= 7? wochentage[@plan.wechsel + c].slice(0..1) : wochentage[@plan.wechsel + c - 7].slice(0..1) %> ||
      <% c = c+1 %>
    <% end %>
    
  
  <% w = Date.new(@plan.jahr,monat).monday %>
  <% while (w.month <= monat && w.year <= @plan.jahr) || (w.month == 12 && w.year < @plan.jahr) do %>
      <br>| <%= w.cweek %> | 
      <% (1..7).each do |wt| %>
        <%= (w + (wt - 1)).strftime("%d") %> |
      <% end %>
      <%= @folge[w.cweek] if @folge && !( monat == 12 && w.cweek == 1 ) %> |
    <% w = w+7 %>
  <% end %>
<% end %>

app/views/plans/show.html.erb
<h2>Plan für <%= @plan.jahr %></h2>

<%= render "plan" %>

app/views/plans/uebernehmen.js.erb
$("#plan").html('<%= escape_javascript(render 'plan') %>')

app/views/plans/update.js.erb
$("#plan").html('<%= escape_javascript(render 'tn_liste' ) %>')